microsoft/Phi-3-mini-4k-instruct:
  per_device_train_batch_size: 2  # Slightly larger batch size per step
  gradient_accumulation_steps: 16  # Effective batch size of 32
  num_train_epochs: 10  # Comprehensive training
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1