Qwen/Qwen1.5-0.5B:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2
  num_train_epochs: 3
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1

Qwen/Qwen1.5-1.8B:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  num_train_epochs: 3
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

Qwen/Qwen1.5-7B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

google/gemma-2b:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  num_train_epochs: 3
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

google/gemma-7b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

microsoft/Phi-3-mini-4k-instruct:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  num_train_epochs: 3
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1
